//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netwise.XrmToolBox.RolesHelper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FetchQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FetchQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netwise.XrmToolBox.RolesHelper.FetchQueries", typeof(FetchQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; output-format=&quot;xml-platform&quot; mapping=&quot;logical&quot; distinct=&quot;false&quot; no-lock=&quot;true&quot; &gt;
        ///    &lt;entity name=&quot;privilege&quot; &gt;
        ///        &lt;attribute name=&quot;privilegeid&quot; /&gt;
        ///        &lt;attribute name=&quot;accessright&quot; /&gt;
        ///        &lt;attribute name=&quot;name&quot; /&gt;
        ///        &lt;filter&gt;
        ///            &lt;condition attribute=&quot;privilegeid&quot; operator=&quot;eq&quot; value=&quot;{0}&quot; /&gt;
        ///        &lt;/filter&gt;
        ///    &lt;/entity&gt;
        ///&lt;/fetch&gt;.
        /// </summary>
        internal static string GetPrivilegeById {
            get {
                return ResourceManager.GetString("GetPrivilegeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; output-format=&quot;xml-platform&quot; mapping=&quot;logical&quot; distinct=&quot;false&quot; no-lock=&quot;true&quot; &gt;
        ///  &lt;entity name=&quot;privilege&quot; &gt;
        ///    &lt;attribute name=&quot;privilegeid&quot; /&gt;
        ///    &lt;attribute name=&quot;accessright&quot; /&gt;
        ///    &lt;attribute name=&quot;name&quot; /&gt;
        ///  &lt;/entity&gt;
        ///&lt;/fetch&gt;.
        /// </summary>
        internal static string GetPrivileges {
            get {
                return ResourceManager.GetString("GetPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; output-format=&quot;xml-platform&quot; mapping=&quot;logical&quot; distinct=&quot;false&quot; no-lock=&quot;true&quot; &gt;
        ///    &lt;entity name=&quot;roleprivileges&quot; &gt;
        ///        &lt;attribute name=&quot;privilegedepthmask&quot; /&gt;
        ///        &lt;attribute name=&quot;privilegeid&quot; /&gt;
        ///        &lt;attribute name=&quot;roleprivilegeid&quot; /&gt;
        ///        &lt;attribute name=&quot;roleid&quot; /&gt;
        ///        &lt;filter&gt;
        ///            &lt;condition attribute=&quot;roleid&quot; operator=&quot;eq&quot; value=&quot;{0}&quot; /&gt;
        ///        &lt;/filter&gt;
        ///    &lt;/entity&gt;
        ///&lt;/fetch&gt;.
        /// </summary>
        internal static string GetPrivilegesForRole {
            get {
                return ResourceManager.GetString("GetPrivilegesForRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; output-format=&quot;xml-platform&quot; mapping=&quot;logical&quot; distinct=&quot;false&quot; no-lock=&quot;true&quot; &gt;
        ///  &lt;entity name=&quot;role&quot; &gt;
        ///    &lt;attribute name=&quot;name&quot; /&gt;
        ///    &lt;attribute name=&quot;roleid&quot; /&gt;
        ///  &lt;/entity&gt;
        ///&lt;/fetch&gt;.
        /// </summary>
        internal static string GetRoles {
            get {
                return ResourceManager.GetString("GetRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch mapping=&quot;logical&quot; version=&quot;1.0&quot; &gt;
        ///    &lt;entity name=&quot;systemuser&quot; &gt;
        ///        &lt;attribute name=&quot;fullname&quot; /&gt;
        ///        &lt;filter&gt;
        ///            &lt;condition attribute=&quot;systemuserid&quot; operator=&quot;eq&quot; value=&quot;{0}&quot; /&gt;
        ///        &lt;/filter&gt;
        ///        &lt;link-entity name=&quot;systemuserroles&quot; from=&quot;systemuserid&quot; to=&quot;systemuserid&quot; &gt;
        ///            &lt;link-entity name=&quot;role&quot; from=&quot;roleid&quot; to=&quot;roleid&quot; &gt;
        ///                &lt;attribute name=&quot;name&quot; /&gt;
        ///                &lt;attribute name=&quot;roleid&quot; /&gt;
        ///            &lt;/link-entity&gt;
        ///        &lt;/link-e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetRolesForUser {
            get {
                return ResourceManager.GetString("GetRolesForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; output-format=&quot;xml-platform&quot; mapping=&quot;logical&quot; distinct=&quot;false&quot; no-lock=&quot;true&quot; &gt;
        ///  &lt;entity name=&quot;systemuser&quot; &gt;
        ///    &lt;attribute name=&quot;fullname&quot; /&gt;
        ///    &lt;attribute name=&quot;systemuserid&quot; /&gt;
        ///  &lt;/entity&gt;
        ///&lt;/fetch&gt;.
        /// </summary>
        internal static string GetUsers {
            get {
                return ResourceManager.GetString("GetUsers", resourceCulture);
            }
        }
    }
}
